[package]
name = "redis-starter-rust"
version = "0.1.0"
authors = ["David Harkness <dharkness@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
mio = "0.8.11"
